### PR TITLE
Fix cropping info missing in EbH265EncStreamHeader issue

### PR DESCRIPTION
**Pull request by jsunintel**
Solved https://github.com/OpenVisualCloud/SVT-HEVC/issues/319.

### CODE REVIEW

**Comment by jsunintel** [comment]
@lijing0010 @kelvinhu325 @tianjunwork @hassount

**Comment by jsunintel** [comment]
Updating the values of conformanceWindowFlag and croppingXXXOffset in ResourceCoordinationKernel is too late, and causes those info not up-to-date in the SPS got from EbH265EncStreamHeader.

**Comment by lijing0010** [comment]
@tianjunwork , seems something wrong with CI here

**Comment by tianjunwork** [comment]
Hi @lijing0010 Jing, there is a 50G limit on storage for appveyor. `Maximum allowed artifact storage size of 50000 Mb will be exceeded`. Recently, somehow we got this error for HEVC and VP9.

**Comment by jsunintel** [comment]
> 
> 
> Hi @lijing0010 Jing, there is a 50G limit on storage for appveyor. `Maximum allowed artifact storage size of 50000 Mb will be exceeded`. Recently, somehow we got this error for HEVC and VP9.

Hi @tianjunwork  what do I need to do about this?

**Comment by tianjunwork** [comment]
Hi @jsunintel Jing, the appveyor error has nothing to do with your PR.

**Pull request merged**
