### PR TITLE
[ASM_SSE2] fixed the output mismatching issue with ASM enabled and disabled (Issue #281).

### PR DESCRIPTION
**Pull request by Austin-Hu**
When gathering SAO statistics for each LCU, the invalid samples
beyond the right edge of LCU shouldn't be counted, although the
use SSE2 intrinsics can only support __m128i data type. So fixed
the issue for SAO BO counting, as the invalid samples are always
0 and would be counted into BO index 0 containing sample value 0~7.

As for EO, all of the C_DEFAULT implementations
(such as GatherSaoStatisticsLcuLossy_62x62) will shifts edge index
2 and 3, with 3 and 4 separately. And the SSE2 implementation
(countEdge) doesn't handle edge index. So the encoded outputs
wouldn't have bit diff, although the EO diffs and counts of edge
index 4 have some gap, between ASM enabled and disabled.

Signed-off-by: Austin Hu <austin.hu@intel.com>

### CODE REVIEW

**Comment by tianjunwork** [comment]
Hi Austin:
There are build errors on Windows:
(ClCompile target) -> 
  C:\projects\svt-hevc-lopps\Source\Lib\ASM_SSE2\EbSaoStatistics_Intrinsic_SSE2.c(96,38): error C2057:  expected constant expression [C:\projects\svt-hevc-lopps\Build\Source\Lib\ASM_SSE2\HEVC_ASM_SSE2.vcxproj]
  C:\projects\svt-hevc-lopps\Source\Lib\ASM_SSE2\EbSaoStatistics_Intrinsic_SSE2.c(96,38): error C2466:  cannot allocate an array of constant size 0 [C:\projects\svt-hevc-lopps\Build\Source\Lib\ASM_SSE2\HEVC_ASM_SSE2.vcxproj]
  C:\projects\svt-hevc-lopps\Source\Lib\ASM_SSE2\EbSaoStatistics_Intrinsic_SSE2.c(96,39): error C2133:  'validSample': unknown size [C:\projects\svt-hevc-lopps\Build\Source\Lib\ASM_SSE2\HEVC_ASM_SSE2.vcxproj]

**Comment by ttrigui** [comment]
The fix looks legit however I'm not sure how this will impact the speed. Probably a better solution would be to call countBand only when needed.
a simple solution can be something similar to this:
  if( 7 < colCountDiv2)
            {
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 0), _mm_extract_epi16(diff, 0), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 1), _mm_extract_epi16(diff, 1), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 2), _mm_extract_epi16(diff, 2), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 3), _mm_extract_epi16(diff, 3), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 4), _mm_extract_epi16(diff, 4), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 5), _mm_extract_epi16(diff, 5), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 6), _mm_extract_epi16(diff, 6), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 7), _mm_extract_epi16(diff, 7), validSample);
            }
            else if (6 < colCountDiv2)
            {
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 0), _mm_extract_epi16(diff, 0), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 1), _mm_extract_epi16(diff, 1), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 2), _mm_extract_epi16(diff, 2), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 3), _mm_extract_epi16(diff, 3), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 4), _mm_extract_epi16(diff, 4), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 5), _mm_extract_epi16(diff, 5), validSample);
                countBand(boDiff, boCount, _mm_extract_epi16(cat, 6), _mm_extract_epi16(diff, 6), validSample);
            }
else if (5 < colCountDiv2)
{........

**Comment by 1480c1** [comment]
@ttrigui, please try to use code blocks, they help differentiate between what you are trying to represent as code and the rest, plus it helps with keeping formatting etc

https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by ttrigui** [comment]
@1480c1 thank you. I hope now it looks better.

**Comment by Austin-Hu** [comment]
Hi @ttrigui ,

Either way is OK, although the ideal implementation should loop calling countBand but we can not use variable as the 2nd argument of _mm_extract_epi16() as I mentioned in the comments. I was just thinking to make the GatherSaoStatisticsLcu_BT_SSE2() function as shorter as possible :p. Thanks!

**Comment by ttrigui** [comment]
@Austin-Hu Correct the second argument to _mm_extract_epi16() cannot be variable which is why I suggeted a solution with an if condition. I still believe that the latter is more efficient as it has less checks and no extra code.

**Comment by tianjunwork** [comment]
Thank you @ttrigui for reviewing the PR. Both implementation is good from different perspective. I think a more maintainable/readable, clearer coding style is worth the sacrifice of a few if cycle. I will merge the PR for closing the bug. Could @Austin-Hu do a benchmark later to compare the performance? Thank you both!

**Comment by Austin-Hu** [comment]
BTW, I’ve verified the 3 reported cases (in Issue [#281](https://github.com/OpenVisualCloud/SVT-HEVC/issues/281)) with several times, with and without this PR applied, and there wasn’t any performance gap (normally +/- 2 FPS) between them. And I would notice any performance regression once reported (from validation team). Thanks!

**Pull request merged**
