### PR TITLE
ffmpeg: Move lines to allow applying on master, 4.3, and 4.2

### PR DESCRIPTION
**Pull request by 1480c1**
# Description

Move some of the lines to allow patching the master branch, 4.3, and 4.2 with the same file

tested with ffmpeg tags n4.2*, n4.3*, and n4.4-dev
tested with ffmpeg branch [master](https://github.com/FFmpeg/FFmpeg/commit/1c7e55dd504245d71444fac1a73e5370cc76fede), release/4.2, and release/4.3 

@guojiansheng0925 can you please review?

# Issue

# Author(s)
@1480c1 

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by guojiansheng0925** [comment]
Hi @1480c1 , The patch looks good and I have tested it. But I can not find your name in Signed-off-by list. How did you make the patch?

**Comment by 1480c1** [comment]
Hi, my workflow usually looks like

```bash
cd FFmpeg
git fetch --all
git reset --hard upstream/master
git am -3 ../SVT-HEVC/ffmpeg_plugin/0001*
# Fix conflicts
git add # conflicting files
git am --continue
git format-patch upstream/master
```

Since my changes don't actually add code that changes the logical output of the patch nor review and verify the code within myself, I did not sign off on it. If it's preferred, I can sign off on the patch

**Comment by tianjunwork** [comment]
@1480c1 your choice of adding sign-off, which shows your contribution to this patch.

**Comment by 1480c1** [comment]
Then I will wait until I fully review the patch and make sure it's something I am content with adding my name to before signing off

**Comment by 1480c1** [comment]
added my signoff

**Review by guojiansheng0925 — APPROVED** [review]

**Pull request merged**
