### PR TITLE
Appveyor: Add debug and basic encoding tests along with mingw builds

### LINKED ISSUE #332: Add Appveyor debug build and basic tests.

### PR DESCRIPTION
**Pull request by 1480c1**
closes #332

Right now the debug msvc build is failing as noted in #331

Right now investigating into properly using ccache for mingw-w64 gcc and maybe sccache for both gcc and cl.exe if possible

### CODE REVIEW

**Comment by 1480c1** [comment]
Right now, it takes a bit of time. Tempted to move over one of the configuration to travis-ci (Maybe the mingw-w64 one) since appveyor only allows single job concurrency for open source projects while travis-ci can do 4.
Especially since travis-ci's linux jobs are much faster, leaving more time for windows jobs to start up (The startup times on both ci's are atrocious, but appveyor's windows support is generally better)

**Comment by tianjunwork** [comment]
Hi @1480c1, Thanks for this contribution. Windows build is not checked by internal CI. So appveyor is important to do sanity check for windows builds.
@Austin-Hu said vs2019 debug build works fine in #331. Did you see it is failing?

**Comment by 1480c1** [comment]
https://ci.appveyor.com/project/1480c1/svt-hevc/builds/26867415/job/cp3b931e2od4rik5

yes, both on appveyor and locally on my laptop

**Comment by tianjunwork** [comment]
Good. It means that your script is working as expected:)

**Pull request merged**
