### PR TITLE
Issues/364

### PR DESCRIPTION
**Pull request by Austin-Hu**

### CODE REVIEW

**Comment by 1480c1** [comment]
@austin-hu

https://help.github.com/en/articles/closing-issues-using-keywords#closing-an-issue-in-the-same-repository

**Comment by Austin-Hu** [comment]
> @Austin-Hu
> 
> https://help.github.com/en/articles/closing-issues-using-keywords#closing-an-issue-in-the-same-repository

Thanks, @1480c1 . You'd ask me to reference this PR to the issue #364 , correct? Sorry that I'm getting familiar with the github usage, as I used gerrit before...

**Comment by 1480c1** [comment]
I meant to point out that you can add keywords to the PR's description to autoclose an issue

like: `Fixes #364` or `Closes #364` and when this PR is merged, github will auto-close the issue for you

**Comment by Austin-Hu** [comment]
> I meant to point out that you can add keywords to the PR's description to autoclose an issue
> 
> like: `Fixes #364` or `Closes #364` and when this PR is merged, github will auto-close the issue for you

Thanks, @1480c1 ! I got to know that in your link you pasted :)

**Pull request merged**
