### PR TITLE
appveyor.yml fix msvc build

### PR DESCRIPTION
**Pull request by 1480c1**

### CODE REVIEW

**Comment by tianjunwork** [comment]
Hi @1480c1, are you done with this PR? can I merge?
The icon appveyor in the SVT-HEVC main page shows "failing": the Project not found or access denied. Do you know what is the reason? Thx.

**Comment by 1480c1** [comment]
Probably because it's not enabled on appveyor side. This PR is mergable and done

**Comment by 1480c1** [comment]
Someone with admin permission needs to enable

**Comment by 1480c1** [comment]
Maybe because we changed from Intel to ovc

**Comment by tianjunwork** [comment]
Hi @1480c1 I added the projects in appveyor. Hevc build passed. Thx. But it is for my own folk. I guess the owner of OVC has to add SVT-HEVC/VP9/AV1 projects in appveyor?

**Comment by 1480c1** [comment]
Yes

**Pull request merged**
