### PR TITLE
Build.sh: Change to use bin sh instead of bash

### PR DESCRIPTION
**Pull request by 1480c1**

### CODE REVIEW

**Comment by tianjunwork** [comment]
Build error with clang, \["CMAKE\_EFLAGS=\\"-DBUILD\_SHARED\_LIBS=OFF\\""\]

**Comment by 1480c1** [comment]
Can you change the set -e to set-ex and rerun?

**Comment by 1480c1** [comment]
I can't seem to replicate, how did you run the script?

**Comment by tianjunwork** [comment]
I rerun the job. Now it is passing.

**Pull request merged**
