### PR TITLE
Conflicts: Fix conflicts with SVT-AV1

### PR DESCRIPTION
**Pull request by 1480c1**
Should the prefix be `EbHevc` or `eb_hevc_`?

### CODE REVIEW

**Comment by Austin-Hu** [comment]
Hi @1480c1 ,

Thanks for your contribution on this to make the encoders aligned in the future! I believe you have some script or rapid way for these changes. So I prefer to hold this PR for some time, till the PR #70 is merged after v1.4.2 as it's a big change targetting for the CRF feature. After PR #70 is merged, you can amend this PR and we will make it go through the merging process. How do you think about it?

Thanks for understanding!

**Comment by 1480c1** [comment]
I think it may be that the particular cpu that the job ran on was probably very slow.



> Hi @1480c1 ,
> 
> Thanks for your contribution on this to make the encoders aligned in the future! I believe you have some script or rapid way for these changes. So I prefer to hold this PR for some time, till the PR #70 is merged after v1.4.2 as it's a big change targetting for the CRF feature. After PR #70 is merged, you can amend this PR and we will make it go through the merging process. How do you think about it?
> 
> Thanks for understanding!

I explicitly made sure that there will be no merge conflicts between #70

You can test this by

```bash
git clone https://github.com/OpenVisualCloud/SVT-HEVC.git
cd SVT-HEVC
git fetch origin pull/429/head
git checkout FETCH_HEAD
git fetch origin pull/70/head
git merge FETCH_HEAD
```

And if there is a merge conflict, git should tell you at the last command

**Comment by 1480c1** [comment]
Although I do not think so, I can capitalize the first letter after Hevc to make sure they are PascalCase if wanted

**Comment by Austin-Hu** [comment]
> I think it may be that the particular cpu that the job ran on was probably very slow.
> 
> > Hi @1480c1 ,
> > Thanks for your contribution on this to make the encoders aligned in the future! I believe you have some script or rapid way for these changes. So I prefer to hold this PR for some time, till the PR #70 is merged after v1.4.2 as it's a big change targetting for the CRF feature. After PR #70 is merged, you can amend this PR and we will make it go through the merging process. How do you think about it?
> > Thanks for understanding!
> 
> I explicitly made sure that there will be no merge conflicts between #70
> 
> You can test this by
> 
> ```shell
> git clone https://github.com/OpenVisualCloud/SVT-HEVC.git
> cd SVT-HEVC
> git fetch origin pull/429/head
> git checkout FETCH_HEAD
> git fetch origin pull/70/head
> git merge FETCH_HEAD
> ```
> 
> And if there is a merge conflict, git should tell you at the last command

Thanks, @1480c1 ! I confirmed that there isn't any confliction between the 2 PRs. The PR looks good to me, unless you'd rename some with PascalCase.

**Comment by 1480c1** [comment]
force-pushed because I forgot to add `--signoff`

**Comment by 1480c1** [comment]
@hassount, is this PR okay?

@Austin-Hu, I can open a PR against the crf branch if there are any changed symbols/symbols that need to be changed after this is merged if you want

**Comment by Austin-Hu** [comment]
> @hassount, is this PR okay?
> 
> @Austin-Hu, I can open a PR against the crf branch if there are any changed symbols/symbols that need to be changed after this is merged if you want

Hi @1480c1 , the PR looks good to me, and we plan to merge it after v1.4.2 release soon.

**Pull request merged**
